auth_enabled: false

server:
  http_listen_port: ${loki_port}
  log_level: "warn"
  grpc_server_max_recv_msg_size: 104857600  # 100 Mb
  grpc_server_max_send_msg_size: 104857600  # 100 Mb

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
%{ if provider_name == "gcp" }
  gcs:
    bucket_name: "${bucket_name}"
    chunk_buffer_size: 2097152  # 2MB
%{ endif }
%{ if provider_name == "aws" }
  aws:
    region: "${aws_region}"
    bucketnames: "${bucket_name}"
    s3forcepathstyle: false
%{ endif }
  tsdb_shipper:
    active_index_directory: /loki/tsdb-shipper-active
    cache_location: /loki/tsdb-shipper-cache
    cache_ttl: 1h

chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 2048
      ttl: 30m

query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 2
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 2048
        ttl: 30m

ingester_client:
  grpc_client_config:
    max_recv_msg_size: 104857600  # 100 Mb
    max_send_msg_size: 104857600  # 100 Mb

ingester:
  chunk_idle_period: 10m
  chunk_encoding: snappy
  max_chunk_age: 15m
  chunk_target_size: 1048576  # 1MB
  wal:
    dir: /loki/wal
    enabled: false
    flush_on_shutdown: true

schema_config:
  configs:
%{ if provider_name == "gcp" }
    - from: 2024-03-05
      store: tsdb
      object_store: gcs
      schema: v12
      index:
        prefix: loki_index_
        period: 24h
%{ if loki_use_v13_schema_from != "" }
    - from: ${loki_use_v13_schema_from}
      store: tsdb
      object_store: gcs
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
%{ endif }
%{ endif }
%{ if provider_name == "aws" }
    - from: 2024-03-05
      store: tsdb
      object_store: aws
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
%{ endif }

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
%{ if provider_name == "gcp" }
  delete_request_store: gcs
%{ endif }
%{ if provider_name == "aws" }
  delete_request_store: aws
%{ endif }

# The bucket lifecycle policy should be set to delete objects after MORE than the specified retention period
limits_config:
  retention_period: 168h
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 500
  per_stream_rate_limit: "80MB"
  per_stream_rate_limit_burst: "240MB"
  max_streams_per_user: 0
  split_queries_by_interval: 30m
  max_global_streams_per_user: 0
  unordered_writes: true
  reject_old_samples_max_age: 168h

  allow_structured_metadata: false  # enable after enabling schema v13
